name: todo_list
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0 <4.0.0'

dependencies:
  ## SDK
  flutter:
    sdk: flutter
  collection: any
  meta: any

  ## BLoC
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5

  ## Storage
  drift: ^2.18.0
  sqlite3: ^2.4.3
  sqlite3_flutter_libs: ^0.5.22

  ## Code generation
  freezed_annotation: ^2.4.1

  ## Navigation
  go_router: ^14.1.3

  ## Utils
  path: ^1.9.0
  path_provider: ^2.1.3

  ## DI
  get_it: ^7.7.0
  injectable: ^2.4.2

dev_dependencies:
  ## Test
  flutter_test:
    sdk: flutter

  ## Lint
  flutter_lints: ^4.0.0

  ## Code generation
  build_runner: ^2.4.9
  drift_dev: ^2.18.0
  freezed: ^2.5.2
  go_router_builder: ^2.7.0
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
